"""
Recommendation Agent - Response Schema

Defines the structured recommendation output returned to the orchestrator
or frontend dashboard after the agent analyses all upstream agent data.
"""

from pydantic import BaseModel, Field
from typing import Optional


class RecommendationResponse(BaseModel):
    """
    Full recommendation report generated by the Recommendation Agent.

    Covers five recommendation dimensions plus an executive summary
    and an overall risk classification.
    """

    executive_summary: str = Field(
        ...,
        description="High-level summary of the current manufacturing situation and key actions required.",
        examples=["Demand significantly exceeds current inventory. Immediate production ramp-up is advised."],
    )
    production: str = Field(
        ...,
        description="Actionable production recommendation.",
        examples=["Increase production output by 20% to close the demand-inventory gap within the planning period."],
    )
    inventory: str = Field(
        ...,
        description="Inventory management recommendation.",
        examples=["Replenish safety stock immediately. Current level is below the reorder point."],
    )
    supplier: str = Field(
        ...,
        description="Supplier / procurement recommendation.",
        examples=["Monitor active supplier delay closely. Consider activating a secondary supplier."],
    )
    risk: str = Field(
        ...,
        description="Overall risk level: Low | Medium | High | Critical.",
        examples=["High"],
    )
    risk_factors: Optional[list[str]] = Field(
        default=None,
        description="List of individual risk factors identified during analysis.",
        examples=[["Supplier delay active", "Inventory below safety stock", "High capacity utilization"]],
    )
    ai_enhanced: bool = Field(
        default=False,
        description="True when the recommendation was generated or enhanced by Gemini AI; False for rule-based output.",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "executive_summary": (
                    "Demand significantly exceeds current inventory. "
                    "Immediate production ramp-up is advised."
                ),
                "production": "Increase production output by 20% to close the demand-inventory gap within the planning period.",
                "inventory": "Replenish safety stock immediately. Current level is below the reorder point.",
                "supplier": "Monitor active supplier delay closely. Consider activating a secondary supplier.",
                "risk": "High",
                "risk_factors": [
                    "Supplier delay active",
                    "Inventory below safety stock",
                    "High capacity utilization",
                ],
                "ai_enhanced": False,
            }
        }
    }
