"""
Recommendation Agent - Response Schema

Defines the structured executive recommendation report returned to the manager or dashboard.
"""

from pydantic import BaseModel, Field
from typing import Optional, List


class RecommendationResponse(BaseModel):
    """
    Full recommendation report generated by the Recommendation Agent.

    Includes operational decisions (production, inventory, supplier),
    risk analysis, priority classification, AI confidence score, and business impact.
    """

    executive_summary: str = Field(
        ...,
        description="High-level summary of the manufacturing situation and key strategic focus.",
        examples=["Demand is expected to increase significantly due to seasonal heatwave surge."],
    )
    production: str = Field(
        ...,
        description="Actionable production recommendation.",
        examples=["Increase production by 20%."],
    )
    inventory: str = Field(
        ...,
        description="Inventory management recommendation.",
        examples=["Increase safety stock by 15%."],
    )
    supplier: str = Field(
        ...,
        description="Supplier and procurement recommendation.",
        examples=["Use alternate supplier due to active lead-time delay."],
    )
    risk: str = Field(
        ...,
        description="Overall risk classification: Low | Medium | High | Critical.",
        examples=["Medium"],
    )
    priority: str = Field(
        default="High",
        description="Strategic priority classification: Normal | High | Critical.",
        examples=["High"],
    )
    confidence: str = Field(
        default="96%",
        description="AI Confidence score percentage.",
        examples=["96%"],
    )
    business_impact: Optional[str] = Field(
        default="High business impact: mitigates potential stockouts and protects estimated 18-25% revenue margin.",
        description="Summary of financial or operational business impact.",
    )
    priority_actions: Optional[List[str]] = Field(
        default=None,
        description="Ordered list of immediate strategic actions.",
        examples=[["Ramp up production by 20%", "Order 15% extra safety stock", "Activate alternate supplier B"]],
    )
    risk_factors: Optional[List[str]] = Field(
        default=None,
        description="Key risk factors identified.",
        examples=[["Supplier delay active (4 days)", "Demand exceeds current stock"]],
    )
    ai_enhanced: bool = Field(
        default=False,
        description="Indicates whether the response was generated or enhanced by Gemini/LLM AI.",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "executive_summary": "Demand is expected to increase significantly.",
                "production": "Increase production by 20%.",
                "inventory": "Increase safety stock.",
                "supplier": "Use alternate supplier.",
                "risk": "Medium",
                "priority": "High",
                "confidence": "96%",
                "business_impact": "High business impact: mitigates potential stockouts.",
                "priority_actions": [
                    "Increase production by 20%",
                    "Increase safety stock buffer",
                    "Use alternate supplier",
                ],
                "ai_enhanced": False,
            }
        }
    }
